/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DP.SastreDP;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alienware
 */
public class VentanaAdministracionSastre extends javax.swing.JFrame {

    /**
     * Creates new form VentanaAdministracionSastre
     */
    private SastreDP sdp;
    boolean isEdit = false;
    
    public VentanaAdministracionSastre() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tf_cods = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tf_ceds = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tf_noms = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf_tels = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tf_nacs = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tf_dirs = new javax.swing.JTextField();
        bt_guardars = new javax.swing.JButton();
        bt_cancelars = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lb_mensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Código de Sastre (S-XXXX)");

        tf_cods.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_codsFocusLost(evt);
            }
        });

        jLabel2.setText("Cédula");

        jLabel3.setText("Nombre");

        jLabel4.setText("Teléfono");

        jLabel5.setText("Año de nacimiento (dd-mm-aaaa)");

        jLabel6.setText("Dirección");

        bt_guardars.setText("GUARDAR");
        bt_guardars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_guardarsActionPerformed(evt);
            }
        });

        bt_cancelars.setText("CANCELAR");
        bt_cancelars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cancelarsActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel7.setText("ADMINISTRACIÓN DE SASTRES");

        jButton1.setText("ELIMINAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lb_mensaje.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_guardars)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jButton1)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_nacs, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_dirs, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_tels, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_noms, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_ceds, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_cods, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_cancelars, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(29, 29, 29)
                .addComponent(lb_mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_cods, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_ceds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tf_noms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tf_tels, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tf_nacs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tf_dirs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_guardars)
                            .addComponent(bt_cancelars))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(lb_mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_codsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_codsFocusLost
        String codigoSastre = tf_cods.getText();
        this.sdp = new SastreDP();
        this.sdp.setCodigoSastre(codigoSastre);

        boolean verificacion = this.sdp.verificarSastre();
        
        if (verificacion==false){
            lb_mensaje.setText("SASTRE DISPONIBLE PARA INGRESO");
            this.tf_ceds.setText("");
            this.tf_dirs.setText("");
            this.tf_nacs.setText("");
            this.tf_noms.setText("");
            this.tf_tels.setText("");
            this.isEdit = false;
        } 
        else{
            lb_mensaje.setText("YA EXISTE ESE SASTRE!!");
            SastreDP sastreBuscado = this.sdp.buscarSastre();
            this.isEdit = true;
            tf_ceds.setText(sastreBuscado.getCedulaSastre());
            tf_dirs.setText(sastreBuscado.getDireccionSastre());
            tf_nacs.setText(sastreBuscado.getNacimientoSastre().toString());
            tf_noms.setText(sastreBuscado.getNombreSastre());
            tf_tels.setText(sastreBuscado.getTelefonoSastre());
        }
        
        System.out.println(verificacion);
    }//GEN-LAST:event_tf_codsFocusLost

    private void limpiar(){
        this.tf_ceds.setText("");
        this.tf_cods.setText("");
        this.tf_dirs.setText("");
        this.tf_nacs.setText("");
        this.tf_tels.setText("");
        this.tf_noms.setText("");
    }
    
    private void bt_guardarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_guardarsActionPerformed
            
            sdp.setCedulaSastre(tf_ceds.getText());
            sdp.setDireccionSastre(tf_dirs.getText());
            String fechaNacimiento = this.tf_nacs.getText();
            try {
                sdp.setNacimientoSastre(new SimpleDateFormat("dd-MM-yyyy").parse(fechaNacimiento));
            } catch (ParseException ex) {
                System.out.println("Fecha mal ingresada: "+ex.toString());
            }
            sdp.setCedulaSastre(this.tf_ceds.getText());
            sdp.setTelefonoSastre(tf_tels.getText());
            sdp.setNombreSastre(this.tf_noms.getText());
            
        if (this.isEdit==false){
            sdp.insertarSastre();
            lb_mensaje.setText("SASTRE INGRESADO");
            this.limpiar();
        }
        else
        {
            sdp.modificarSastre();
            lb_mensaje.setText("SASTRE MODIFICADO");
            this.limpiar();
        }
    }//GEN-LAST:event_bt_guardarsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int resp = JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar el sastre: "+sdp.getCodigoSastre()+"?");
	if(resp==0){
           sdp.eliminarSastre();
           lb_mensaje.setText("SASTRE ELIMINADO");
           this.limpiar();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bt_cancelarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelarsActionPerformed
        this.dispose();
        new VentanaPrincipal().setVisible(true);
    }//GEN-LAST:event_bt_cancelarsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAdministracionSastre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAdministracionSastre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAdministracionSastre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAdministracionSastre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAdministracionSastre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_cancelars;
    private javax.swing.JButton bt_guardars;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lb_mensaje;
    private javax.swing.JTextField tf_ceds;
    private javax.swing.JTextField tf_cods;
    private javax.swing.JTextField tf_dirs;
    private javax.swing.JTextField tf_nacs;
    private javax.swing.JTextField tf_noms;
    private javax.swing.JTextField tf_tels;
    // End of variables declaration//GEN-END:variables
}
