/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DP.SastreDP;
import DP.TareaTextilDP;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Alienware
 */
public class VentanaAdminstracionTareasTextiles extends javax.swing.JFrame {

    /**
     * Creates new form VentanaAdminstracionTareasTextiles
     */
    private TareaTextilDP ttdp;
    boolean isEdit = false;
    public VentanaAdminstracionTareasTextiles() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tf_codtt = new javax.swing.JTextField();
        tf_fechatt = new javax.swing.JTextField();
        tf_tipott = new javax.swing.JTextField();
        tf_destt = new javax.swing.JTextField();
        bt_guardartt = new javax.swing.JButton();
        bt_cancelartt = new javax.swing.JButton();
        bt_eliminartt = new javax.swing.JButton();
        bt_mensajett = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel7.setText("ADMINISTRACIÓN DE TAREAS TEXTILES");

        jLabel1.setText("Código de Tarea Textil");

        jLabel2.setText("Fecha limite Tarea Textil (dd-mm-aaaa)");

        jLabel3.setText("Tipo de Tarea Textil");

        jLabel4.setText("Descripción Tarea Textil");

        tf_codtt.setText("2020");
        tf_codtt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_codttFocusLost(evt);
            }
        });

        tf_tipott.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_tipottActionPerformed(evt);
            }
        });

        bt_guardartt.setText("GUARDAR");
        bt_guardartt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_guardarttActionPerformed(evt);
            }
        });

        bt_cancelartt.setText("CANCELAR");

        bt_eliminartt.setText("ELIMINAR");
        bt_eliminartt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_eliminarttActionPerformed(evt);
            }
        });

        bt_mensajett.setText("YA EXISTE ESA TAREA TEXTIL!!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bt_eliminartt)
                                    .addComponent(bt_guardartt))))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt_cancelartt)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_destt, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_tipott, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_fechatt, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_codtt, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(109, 109, 109)
                                .addComponent(bt_mensajett, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tf_codtt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tf_fechatt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tf_tipott, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tf_destt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(bt_mensajett, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_guardartt)
                    .addComponent(bt_cancelartt))
                .addGap(46, 46, 46)
                .addComponent(bt_eliminartt)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_guardarttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_guardarttActionPerformed
            
            String fechalimite = this.tf_fechatt.getText();
            try {
                ttdp.setFechaLimiteTarea(new SimpleDateFormat("dd-MM-yyyy").parse(fechalimite));
            } catch (ParseException ex) {
                System.out.println("Fecha mal ingresada: "+ex.toString());
            }
            ttdp.setTipoTarea(this.tf_tipott.getText());
            ttdp.setDescripcionTarea(this.tf_destt.getText());
            
            
        if (this.isEdit==false){
            ttdp.insertarTarea();
            bt_mensajett.setText("TAREA TEXTIL INGRESADA");
            this.limpiar();
        }
        else
        {
            ttdp.modificarTarea();
            bt_mensajett.setText("TAREA MODIFICADA");
            this.limpiar();
        }
    }//GEN-LAST:event_bt_guardarttActionPerformed

    private void tf_codttFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_codttFocusLost
        String codigoTareaTextil = tf_codtt.getText();
        this.ttdp = new TareaTextilDP();
        this.ttdp.setCodigoTarea(codigoTareaTextil);

        boolean verificacion = this.ttdp.verificarTarea();
        
        if (verificacion==false){
            bt_mensajett.setText("TAREA TEXTIL DISPONIBLE PARA INGRESO");
            this.tf_destt.setText("");
            this.tf_fechatt.setText("");
            this.tf_tipott.setText("");
            
            this.isEdit = false;
        } 
        else{
            bt_mensajett.setText("YA EXISTE ESA TAREA TEXTIL!!");
            TareaTextilDP TareaTextilBuscada = this.ttdp.buscarTarea();
            this.isEdit = true;
            tf_destt.setText(TareaTextilBuscada.getDescripcionTarea());
            tf_tipott.setText(TareaTextilBuscada.getTipoTarea());
            tf_fechatt.setText(TareaTextilBuscada.getFechaLimiteTarea().toString());
            
        }
        
        System.out.println(verificacion);
    }//GEN-LAST:event_tf_codttFocusLost

    private void bt_eliminarttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_eliminarttActionPerformed
        int resp = JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar la tarea: "+ttdp.getCodigoTarea()+"?");
	if(resp==0){
           ttdp.eliminarTarea();
           bt_mensajett.setText("TAREA ELIMINADA");
           this.limpiar();
        }
    }//GEN-LAST:event_bt_eliminarttActionPerformed

    private void tf_tipottActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_tipottActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_tipottActionPerformed
    private void limpiar(){
        this.tf_codtt.setText("");
        this.tf_destt.setText("");
        this.tf_fechatt.setText("");
        this.tf_tipott.setText("");
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAdminstracionTareasTextiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAdminstracionTareasTextiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAdminstracionTareasTextiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAdminstracionTareasTextiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAdminstracionTareasTextiles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_cancelartt;
    private javax.swing.JButton bt_eliminartt;
    private javax.swing.JButton bt_guardartt;
    private javax.swing.JLabel bt_mensajett;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField tf_codtt;
    private javax.swing.JTextField tf_destt;
    private javax.swing.JTextField tf_fechatt;
    private javax.swing.JTextField tf_tipott;
    // End of variables declaration//GEN-END:variables
}
